# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: github-actions
  directory: ".github/workflows/"
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: "/Templates/Per Tenant Extension/.github/workflows/"
  schedule:
    interval: weekly
  ignore:
    - dependency-name: "microsoft/AL-Go-Actions/*"
- package-ecosystem: github-actions
  directory: "/Templates/AppSource App/.github/workflows/"
  schedule:
    interval: weekly
  ignore:
    - dependency-name: "microsoft/AL-Go-Actions/*"
