lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
markdown: kramdown
remote-theme: pages-themes/midnight@v0.2.0
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
