name: ' Create Online Dev. Environment'

run-name: "Create Online Dev. Environment for [${{ github.ref_name }} / ${{ github.event.inputs.project }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      environmentName:
        description: Name of the online environment
        required: true
      reUseExistingEnvironment:
        description: Reuse environment if it exists
        required: false
        default: 'N'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for Pull Request/COMMIT
        type: boolean

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialization:
    runs-on: [ windows-latest ]
    outputs:
      deviceCode: ${{ steps.authenticate.outputs.deviceCode }}
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
      githubRunner: ${{ steps.ReadSettings.outputs.GitHubRunnerJson }}
      githubRunnerShell: ${{ steps.ReadSettings.outputs.GitHubRunnerShell }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell
          eventId: "DO0093"

      - name: Read settings
        id: ReadSettings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          secrets: 'adminCenterApiCredentials'

      - name: Check AdminCenterApiCredentials / Initiate Device Login (open to see code)
        id: authenticate
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $adminCenterApiCredentials = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:adminCenterApiCredentials))
          if ($adminCenterApiCredentials) {
            Write-Host "AdminCenterApiCredentials provided in secret $($ENV:adminCenterApiCredentialsSecretName)!"
            Add-Content -Encoding UTF8 -path $ENV:GITHUB_STEP_SUMMARY -value "Admin Center Api Credentials was provided in a secret called $($ENV:adminCenterApiCredentialsSecretName). Using this information for authentication."
          }
          else {
            Write-Host "AdminCenterApiCredentials not provided, initiating Device Code flow"
            $ALGoHelperPath = "$([System.IO.Path]::GetTempFileName()).ps1"
            $webClient = New-Object System.Net.WebClient
            $webClient.DownloadFile('https://raw.githubusercontent.com/microsoft/AL-Go-Actions/main/AL-Go-Helper.ps1', $ALGoHelperPath)
            . $ALGoHelperPath
            $BcContainerHelperPath = DownloadAndImportBcContainerHelper -baseFolder $ENV:GITHUB_WORKSPACE
            $authContext = New-BcAuthContext -includeDeviceLogin -deviceLoginTimeout ([TimeSpan]::FromSeconds(0))
            CleanupAfterBcContainerHelper -bcContainerHelperPath $bcContainerHelperPath
            Add-Content -Encoding UTF8 -path $ENV:GITHUB_STEP_SUMMARY -value "AL-Go needs access to the Business Central Admin Center Api and could not locate a secret called $($ENV:adminCenterApiCredentialsSecretName) (https://aka.ms/ALGoSettings#AdminCenterApiCredentialsSecretName)`n`n$($authContext.message)"
            Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "deviceCode=$($authContext.deviceCode)"
          }

  CreateDevelopmentEnvironment:
    runs-on: ${{ fromJson(needs.Initialization.outputs.githubRunner) }}
    defaults:
      run:
        shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
    name: Create Development Environment
    needs: [ Initialization ]
    env:
      deviceCode: ${{ needs.Initialization.outputs.deviceCode }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          get: ghTokenWorkflowSecretName

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          secrets: 'adminCenterApiCredentials,ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: CalculateToken
        id: CalculateToken
        env:
          useGhTokenWorkflow: ${{ github.event.inputs.useGhTokenWorkflow }}
        run: |
          if ($env:useGhTokenWorkflow -eq 'true') {
            $ghToken = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:GHTOKENWORKFLOW))
          } else {
            $ghToken = '${{ secrets.GITHUB_TOKEN }}'
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "ghToken=$ghToken"

      - name: Set AdminCenterApiCredentials
        run: |
          if ($env:deviceCode) {
            $adminCenterApiCredentials = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("{""deviceCode"":""$($env:deviceCode)""}"))
            Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -value "adminCenterApiCredentials=$adminCenterApiCredentials"
          }

      - name: Create Development Environment
        uses: microsoft/AL-Go-Actions/CreateDevelopmentEnvironment@main
        with:
          shell: powershell
          token: ${{ steps.CalculateToken.outputs.ghToken }}
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          environmentName: ${{ github.event.inputs.environmentName }}
          project: ${{ github.event.inputs.project }}
          reUseExistingEnvironment: ${{ github.event.inputs.reUseExistingEnvironment }}
          directCommit: ${{ github.event.inputs.directCommit }}
          adminCenterApiCredentials: ${{ env.adminCenterApiCredentials }}

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        with:
          shell: powershell
          eventId: "DO0093"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
