name: ' Increment Version Number'

run-name: "Increment Version Number in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects (* for all projects)
        required: false
        default: '*'
      versionNumber:
        description: Updated Version Number. Use Major.Minor for absolute change, use +Major.Minor for incremental change.
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for Pull Request/COMMIT
        type: boolean

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  IncrementVersionNumber:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell
          eventId: "DO0096"

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        id: ReadSettings
        if: github.event.inputs.useGhTokenWorkflow == 'true'
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          get: keyVaultName,ghTokenWorkflowSecretName

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        if: github.event.inputs.useGhTokenWorkflow == 'true'
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          settingsJson: ${{ steps.ReadSettings.outputs.SettingsJson }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: CalculateToken
        id: CalculateToken
        env:
          useGhTokenWorkflow: ${{ github.event.inputs.useGhTokenWorkflow }}
        run: |
          if ($env:useGhTokenWorkflow -eq 'true') {
            $ghToken = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:GHTOKENWORKFLOW))
          } else {
            $ghToken = '${{ secrets.GITHUB_TOKEN }}'
          }
          Add-Content -Path $env:GITHUB_OUTPUT -Value "ghToken=$ghToken"

      - name: Increment Version Number
        uses: microsoft/AL-Go-Actions/IncrementVersionNumber@main
        with:
          shell: powershell
          token: ${{ steps.CalculateToken.outputs.ghToken }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          versionNumber: ${{ github.event.inputs.versionNumber }}
          directCommit: ${{ github.event.inputs.directCommit }}
  
      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        with:
          shell: powershell
          eventId: "DO0096"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
