name: ' Increment Version Number'

run-name: "Increment Version Number in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects (* for all projects)
        required: false
        default: '*'
      versionNumber:
        description: Updated Version Number. Use Major.Minor for absolute change, use +Major.Minor for incremental change.
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for Pull Request/COMMIT
        type: boolean
      tempGhTokenWorkflow:
        description: Temporary Access Token to use as GhTokenWorkflow
        required: false
        default: ''

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  IncrementVersionNumber:
    runs-on: [ windows-latest ]
    steps:
      - name: Mask Token
        id: tempGhTokenWorkflow
        run: |
          # Using github.event.inputs.tempGhTokenWorkflow will expose the token in the logs
          $eventPath = Get-Content -Encoding UTF8 -Path $env:GITHUB_EVENT_PATH -Raw | ConvertFrom-Json
          $tempGhTokenWorkflow = $eventPath.inputs.tempGhTokenWorkflow
          if ($tempGhTokenWorkflow) {
            Write-Host "::add-mask::$tempGhTokenWorkflow"
          }
          Add-Content -Encoding UTF8 -Path $ENV:GITHUB_OUTPUT -Value "tempGhTokenWorkflow=$tempGhTokenWorkflow"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell
          eventId: "DO0096"

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'TokenForPush'
          tempGhTokenWorkflow: ${{ steps.tempGhTokenWorkflow.outputs.tempGhTokenWorkflow }}
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Increment Version Number
        uses: microsoft/AL-Go-Actions/IncrementVersionNumber@main
        with:
          shell: powershell
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          versionNumber: ${{ github.event.inputs.versionNumber }}
          directCommit: ${{ github.event.inputs.directCommit }}
  
      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        with:
          shell: powershell
          eventId: "DO0096"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
