name: Increment Version Number

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects (* for all projects)
        required: false
        default: '.'
      versionNumber:
        description: Updated Version Number. Use Major.Minor for absolute change, use +Major.Minor for incremental change.
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: PowerShell

jobs:
  Initialization:
    runs-on: [ windows-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          eventId: "DO0096"

  Update:
    runs-on: [ windows-latest ]
    needs: [ Initialization ]

    steps:
      - name: Increment Version Number
        uses: microsoft/AL-Go-Actions/IncrementVersionNumber@main
        with:
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          versionNumber: ${{ github.event.inputs.versionNumber }}
          directCommit: ${{ github.event.inputs.directCommit }}
  
  PostProcess:
    if: always()
    runs-on: [ windows-latest ]
    needs: [ Initialization, Update ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Finalize the workflow
        id: PostProcess
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        with:
          eventId: "DO0096"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
