name: Update AL-Go System Files

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (only if a change is needed)
        required: false
        default: ''
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: [ windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: microsoft/AL-Go/ReadSettings@main
        with:
          get: KeyVaultName,GhTokenWorkflowSecretName,TemplateUrl,TemplateBranch

      - name: Read secrets
        uses: microsoft/AL-Go/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          settingsJson: ${{ env.Settings }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: Override TemplateUrl
        run: |
          $templateUrl = '${{ github.event.inputs.templateUrl }}'
          if ($templateUrl) {
            Write-Host "Using Template Url: $templateUrl"
            $templateBranch = "$templateUrl@".Split('@')[1]
            $templateUrl = "$templateUrl".Split('@')[0]
            Add-Content -Path $env:GITHUB_ENV -Value "TemplateUrl=$templateUrl"
            Add-Content -Path $env:GITHUB_ENV -Value "TemplateBranch=$templateBranch"
          }

      - name: Update AL-Go system files
        uses: microsoft/AL-Go/CheckForUpdates@main
        with:
          token: ${{ env.ghTokenWorkflow }}
          update: Y
          templateUrl: ${{ env.TemplateUrl }}
          templateBranch: ${{ env.TemplateBranch }}
          directCommit: ${{ github.event.inputs.directCommit }}
