name: ' Update AL-Go System Files'

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (current is {TEMPLATEURL})
        required: false
        default: ''
      downloadLatest:
        description: Download latest from template repository
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  GetBranches:
    runs-on: windows-latest
    name: Get Supported Branches
    outputs:
      SupportedBranches: ${{ steps.DetermineBranches.outputs.Result }}
    steps:
      - name: Checkout
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - name: Read settings
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          get: updateALGoBranches

      - name: Get Supported Branches
        if: ${{ github.event_name != 'workflow_dispatch' }}
        id: GetSupportedBranches
        uses: microsoft/AL-Go-Actions/GetGitBranches@main
        with:
          shell: powershell
          includeBranches: ${{ env.updateALGoBranches }}

      - name: Determine branches to update
        id: DetermineBranches
        run: |
            if ('${{ github.event_name }}' != 'workflow_dispatch') {
              Write-Host "Running Update AL-Go System Files on a schedule."
              Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "Result='${{ steps.GetSupportedBranches.outputs.Branches }}'"
            }
            else {
              Write-Host "Running Update AL-Go System Files on a manual trigger."
              Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "Result='[${{ github.ref_name }}]'"
            }

  UpdateALGoSystemFiles:
    name: "[${{ matrix.branch }}] Update AL-Go System Files"
    needs: [ GetBranches ]
    runs-on: [ windows-latest ]
    strategy:
      matrix:
        branch: ${{ fromJson(needs.GetBranches.outputs.SupportedBranches) }}
      fail-fast: false

    steps:
      - name: Dump Workflow Information
        uses: microsoft/AL-Go-Actions/DumpWorkflowInfo@main
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell
          eventId: "DO0098"

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          get: templateUrl

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Override templateUrl
        env:
          templateUrl: ${{ github.event.inputs.templateUrl }}
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $templateUrl = $ENV:templateUrl
          if ($templateUrl) {
            Write-Host "Using Template Url: $templateUrl"
            Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "templateUrl=$templateUrl"
          }

      - name: Calculate Input
        env:
          directCommit: '${{ github.event.inputs.directCommit }}'
          downloadLatest: ${{ github.event.inputs.downloadLatest }}
          eventName: ${{ github.event_name }}
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $directCommit = $ENV:directCommit
          $downloadLatest = $ENV:downloadLatest
          Write-Host $ENV:eventName
          if ($ENV:eventName -eq 'schedule') {
            Write-Host "Running Update AL-Go System Files on a schedule. Setting DirectCommit and DownloadLatest to true"
            $directCommit = 'true'
            $downloadLatest = 'true'
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "directCommit=$directCommit"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "downloadLatest=$downloadLatest"

      - name: Update AL-Go system files
        uses: microsoft/AL-Go-Actions/CheckForUpdates@main
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          downloadLatest: ${{ env.downloadLatest }}
          update: 'Y'
          templateUrl: ${{ env.templateUrl }}
          directCommit: ${{ env.directCommit }}
          updateBranch: ${{ matrix.branch }}

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        with:
          shell: powershell
          eventId: "DO0098"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
