name: Update AL-Go System Files

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (only if a change is needed)
        required: false
        default: ''
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  initialization:
    runs-on: [ windows-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with: 
          eventId: "DO0098"

  update:
    runs-on: [ windows-latest ]
    needs: [ initialization ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          parentTelemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}
          get: KeyVaultName,GhTokenWorkflowSecretName,TemplateUrl

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          parentTelemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: Override TemplateUrl
        run: |
          $templateUrl = '${{ github.event.inputs.templateUrl }}'
          if ($templateUrl) {
            Write-Host "Using Template Url: $templateUrl"
            Add-Content -Path $env:GITHUB_ENV -Value "TemplateUrl=$templateUrl"
          }

      - name: Update AL-Go system files
        uses: microsoft/AL-Go-Actions/CheckForUpdates@main
        with:
          parentTelemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}
          token: ${{ env.ghTokenWorkflow }}
          update: Y
          templateUrl: ${{ env.TemplateUrl }}
          directCommit: ${{ github.event.inputs.directCommit }}

  postProcess:
    runs-on: [ windows-latest ]
    needs: [ initialization, update ]
    steps:
      - name: Finalizing the workflow
        id: postProcess
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        with: 
          eventId: "DO0098"
          telemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}  