name: Add existing app or test app

on:
  workflow_dispatch:
    inputs:
      url:
        description: Direct Download Url of .app or .zip file
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'
defaults:
  run:
    shell: PowerShell

jobs:
  initialization :
    runs-on: windows-latest
    outputs:
      telemetryScope: ${{ steps.init.outputs.telemetryScope }}
      correlationId: ${{ steps.init.outputs.correlationId }}  
    steps:
      - id: init
        uses: microsoft/AL-Go/InitWorkflow@main
        with: 
          workflowName : "DO0090"

  update:
    runs-on: windows-latest
    needs : [ initialization ]
    steps:
      - name: Add existing app
        uses: microsoft/AL-Go/AddExistingApp@main
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}        
          url: ${{ github.event.inputs.url }}
          directCommit: ${{ github.event.inputs.directCommit }}
