name: CI/CD

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
    branches: 
      - main
      - 'releases/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  initialization :
    runs-on: windows-latest
    outputs:
      telemetryScope: ${{ steps.init.outputs.telemetryScope }}
      correlationId: ${{ steps.init.outputs.correlationId }}  
    steps:
      - id: init
        uses: microsoft/AL-Go/InitWorkflow@main
        with: 
          workflowName : "DO0091"

  CheckForUpdates:
    runs-on: windows-latest
    needs : [ initialization ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: microsoft/AL-Go/ReadSettings@main
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}
          get: TemplateUrl,TemplateBranch

      - name: Check for updates to AL-Go system files
        uses: microsoft/AL-Go/CheckForUpdates@main
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}
          templateUrl: ${{ env.TemplateUrl }}
          templateBranch: ${{ env.TemplateBranch }}
  Analyze:
    runs-on: windows-latest
    needs : [ initialization ]
    outputs:
      projects: ${{ steps.Projects.outputs.projects }}
      projectCount: ${{ steps.Projects.outputs.projectCount }}
      environments: ${{ steps.Environments.outputs.environments }}
      environmentCount: ${{ steps.Environments.outputs.environmentCount }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Projects
        id: Projects
        run: |
          if (Test-Path ".AL-Go" -PathType Container) {
            $projects = @(".")
          }
          else {
            $projects = @(Get-ChildItem -Path $ENV:GITHUB_WORKSPACE -Directory | Where-Object { Test-Path (Join-Path $_.FullName ".AL-Go") -PathType Container } | ForEach-Object { $_.Name })
          }
          if ($projects.Count -eq 1) {
            $projectsJSon = "[$($projects | ConvertTo-Json -compress)]"
          }
          else {
            $projectsJSon = $projects | ConvertTo-Json -compress
          }
          Write-Host "::set-output name=projects::$projectsJson"
          Write-Host "::set-output name=projectCount::$($projects.Count)"
          Write-Host "set-output name=projects::$projectsJson"
          Write-Host "set-output name=projectCount::$($projects.Count)"

      - name: Environments
        id: Environments
        run: |
          $headers = @{ 
            "Authorization" = "token ${{ github.token }}"
            "Accept"        = "application/vnd.github.v3+json"
          }
          $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/environments"
          $environments = @((Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri $url | ConvertFrom-Json).environments | ForEach-Object { $_.Name })
          if ($environments.Count -eq 1) {
            $environmentsJSon = "[$($environments | ConvertTo-Json -compress)]"
          }
          else {
            $environmentsJSon = $environments | ConvertTo-Json -compress
          }
          Write-Host "::set-output name=environments::$environmentsJson"
          Write-Host "::set-output name=environmentCount::$($environments.Count)"
          Write-Host "set-output name=environments::$environmentsJson"
          Write-Host "set-output name=environmentCount::$($environments.Count)"
  Build:
    runs-on: windows-latest
    needs: [ Analyze ]
    strategy:
      matrix:
        project: ${{ fromJson(needs.Analyze.outputs.projects) }}
      fail-fast: false
    name: Build ${{ matrix.project }}
    outputs:
      AppsArtifactsName: ${{ steps.calculateArtifactNames.outputs.AppsArtifactsName }}
      TestAppsArtifactsName: ${{ steps.calculateArtifactNames.outputs.TestAppsArtifactsName }}
      TestResultsArtifactsName: ${{ steps.calculateArtifactNames.outputs.TestResultsArtifactsName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: microsoft/AL-Go/ReadSettings@main
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}
          project: ${{ matrix.project }}

      - name: Read secrets
        uses: microsoft/AL-Go/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}
          settingsJson: ${{ env.Settings }}
          secrets: 'licenseFileUrl,insiderSasToken,CodeSignCertificateUrl,CodeSignCertificatePassword,KeyVaultCertificateUrl,KeyVaultCertificatePassword,KeyVaultClientId'

      - name: Run pipeline
        uses: microsoft/AL-Go/RunPipeline@main
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}
          Project: ${{ matrix.project }}
          settingsJson: ${{ env.Settings }}
          SecretsJson: ${{ env.RepoSecrets }}

      - name: Publish test results
        if: success() || failure()
        uses: mikepenz/action-junit-report@v1
        with:
          check_name: 'Test Report ${{ matrix.project }}'
          report_paths: '${{ matrix.project }}/TestResults*.xml'
          github_token: ${{ github.token }}

      - name: Calculate Artifact names
        id: calculateArtifactNames
        if: success() || failure()
        run: |
          $settings = '${{ env.Settings }}' | ConvertFrom-Json
          $project = '${{ matrix.project }}'
          if ($project -eq ".") { $project = $settings.RepoName }
          $AppsArtifactsName = "$project-Apps-$($settings.repoVersion).$($settings.appBuild).$($settings.appRevision)"
          $TestAppsArtifactsName = "$project-TestApps-$($settings.repoVersion).$($settings.appBuild).$($settings.appRevision)"
          $TestResultsArtifactsName = "$project-TestResults"
          'AppsArtifactsName','TestAppsArtifactsName','TestResultsArtifactsName' | ForEach-Object {
            $value = (Get-Variable -Name $_).Value
            Write-Host "::set-output name=$_::$value"
            Add-Content -Path $env:GITHUB_ENV -Value "$_=$value"
          }

      - name: Publish artifacts - apps
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.appsArtifactsName }}
          path: '${{ matrix.project }}/output/Apps/'
          if-no-files-found: ignore

      - name: Publish artifacts - test apps
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.testAppsArtifactsName }}
          path: '${{ matrix.project }}/output/TestApps/'
          if-no-files-found: ignore

      - name: Publish artifacts - test results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: ${{ env.testResultsArtifactsName }}
          path: '${{ matrix.project }}/TestResults.xml'
          if-no-files-found: ignore

      - name: Cleanup
        if: always()
        uses: microsoft/AL-Go/PipelineCleanup@main
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}
          Project: ${{ matrix.project }}
  Deploy:
    runs-on: windows-latest
    needs: [ Analyze, Build ]
    if: ${{ needs.Analyze.outputs.environmentCount > 0 }}
    strategy:
      matrix:
        environment: ${{ fromJson(needs.Analyze.outputs.environments) }}
      fail-fast: false
    name: Deploy to ${{ matrix.environment }}
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: '${{ github.workspace }}\artifacts'

      - name: Deploy
        uses: microsoft/AL-Go/Deploy@main
        env:
          authContext: '${{ secrets.AuthContext }}'
        with:
          type: 'CD'
          projects: '${{ secrets.Projects }}'
          environmentName: ${{ matrix.environment }}
          artifacts: '${{ github.workspace }}\artifacts'