name: CI/CD

on:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/**'
  workflow_dispatch:

defaults:
  run:
    shell: PowerShell

jobs:
  initialization:
    runs-on: [ windows-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with: 
          eventId: "DO0091"

  CheckForUpdates:
    runs-on: [ windows-latest ]
    needs: [ initialization ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          parentTelemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}
          get: TemplateUrl

      - name: Check for updates to AL-Go system files
        uses: microsoft/AL-Go-Actions/CheckForUpdates@main
        with:
          parentTelemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}
          templateUrl: ${{ env.TemplateUrl }}
  Analyze:
    runs-on: [ windows-latest ]
    needs: [ initialization ]
    outputs:
      projects: ${{ steps.Projects.outputs.projects }}
      projectCount: ${{ steps.Projects.outputs.projectCount }}
      environments: ${{ steps.Environments.outputs.environments }}
      environmentCount: ${{ steps.Environments.outputs.environmentCount }}
      githubRunner: ${{ steps.OutputSettings.outputs.githubRunner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          get: githubRunner,alwaysBuildAllProjects

      - name: Output settings
        id: OutputSettings
        run: |
          $gitHubRunner = "$env:githubRunner".Split(',') | ConvertTo-Json -compress
          Write-Host "::set-output name=githubRunner::$githubRunner"
          Write-Host "set-output name=githubRunner::$githubRunner"

      - name: Projects
        id: Projects
        run: |
          if (Test-Path ".AL-Go" -PathType Container) {
            $projects = @(".")
          }
          else {
            $projects = @(Get-ChildItem -Path $ENV:GITHUB_WORKSPACE -Directory | Where-Object { Test-Path (Join-Path $_.FullName ".AL-Go") -PathType Container } | ForEach-Object { $_.Name })
            Write-Host "Projects: $($projects -join ', ')"
            if (!($ENV:GITHUB_EVENT_NAME -eq "workflow_dispatch" -or "$ENV:alwaysBuildAllProjects" -eq "true")) {
              $headers = @{             
                "Authorization" = "token ${{ github.token }}"
                "Accept" = "application/vnd.github.baptiste-preview+json"
              }
              if ($ENV:GITHUB_EVENT_NAME -eq "pull_request") {
                $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/compare/${{ github.event.pull_request.base.sha }}...${{ github.sha }}"
              }
              else {
                $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/compare/${{ github.event.before }}...${{ github.event.after }}"
              }
              $response = Invoke-WebRequest -Headers $headers -UseBasicParsing -Method GET -Uri $url | ConvertFrom-Json
              $filesChanged = @($response.files | ForEach-Object { $_.filename })
              if ($filesChanged.Count -lt 250) {
                $foldersChanged = @($filesChanged | ForEach-Object { $_.Split('/')[0] } | Select-Object -Unique)
                $projects = @($projects | Where-Object { $foldersChanged -contains $_ })
                Write-Host "Modified projects: $($projects -join ', ')"
              }
            }
          }
          if ($projects.Count -eq 1) {
            $projectsJSon = "[$($projects | ConvertTo-Json -compress)]"
          }
          else {
            $projectsJSon = $projects | ConvertTo-Json -compress
          }
          Write-Host "::set-output name=projects::$projectsJson"
          Write-Host "::set-output name=projectCount::$($projects.Count)"
          Write-Host "set-output name=projects::$projectsJson"
          Write-Host "set-output name=projectCount::$($projects.Count)"

      - name: Environments
        id: Environments
        run: |
          $headers = @{ 
            "Authorization" = "token ${{ github.token }}"
            "Accept"        = "application/vnd.github.v3+json"
          }
          $url = "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/environments"
          $environments = @((Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri $url | ConvertFrom-Json).environments | Where-Object { $_.Name -notlike '* (Production)' } | ForEach-Object { $_.Name })
          if ($environments.Count -eq 1) {
            $environmentsJSon = "[$($environments | ConvertTo-Json -compress)]"
          }
          else {
            $environmentsJSon = $environments | ConvertTo-Json -compress
          }
          Write-Host "::set-output name=environments::$environmentsJson"
          Write-Host "::set-output name=environmentCount::$($environments.Count)"
          Write-Host "set-output name=environments::$environmentsJson"
          Write-Host "set-output name=environmentCount::$($environments.Count)"
  Build:
    needs: [ Analyze ]
    runs-on: ${{ fromJson(needs.Analyze.outputs.githubRunner) }}
    strategy:
      matrix:
        project: ${{ fromJson(needs.Analyze.outputs.projects) }}
      fail-fast: false
    name: Build ${{ matrix.project }}
    outputs:
      AppsArtifactsName: ${{ steps.calculateArtifactNames.outputs.AppsArtifactsName }}
      TestAppsArtifactsName: ${{ steps.calculateArtifactNames.outputs.TestAppsArtifactsName }}
      TestResultsArtifactsName: ${{ steps.calculateArtifactNames.outputs.TestResultsArtifactsName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          parentTelemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}
          project: ${{ matrix.project }}

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          parentTelemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'licenseFileUrl,insiderSasToken,CodeSignCertificateUrl,CodeSignCertificatePassword,KeyVaultCertificateUrl,KeyVaultCertificatePassword,KeyVaultClientId'

      - name: Run pipeline
        uses: microsoft/AL-Go-Actions/RunPipeline@main
        with:
          parentTelemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}
          Project: ${{ matrix.project }}
          settingsJson: ${{ env.Settings }}
          SecretsJson: ${{ env.RepoSecrets }}

      - name: Publish test results
        if: success() || failure()
        uses: mikepenz/action-junit-report@v1
        with:
          check_name: 'Test Report ${{ matrix.project }}'
          report_paths: '${{ matrix.project }}/TestResults*.xml'
          github_token: ${{ github.token }}

      - name: Calculate Artifact names
        id: calculateArtifactNames
        if: success() || failure()
        run: |
          $settings = '${{ env.Settings }}' | ConvertFrom-Json
          $project = '${{ matrix.project }}'
          if ($project -eq ".") { $project = $settings.RepoName }
          $AppsArtifactsName = "$project-Apps-$($settings.repoVersion).$($settings.appBuild).$($settings.appRevision)"
          $TestAppsArtifactsName = "$project-TestApps-$($settings.repoVersion).$($settings.appBuild).$($settings.appRevision)"
          $TestResultsArtifactsName = "$project-TestResults"
          'AppsArtifactsName','TestAppsArtifactsName','TestResultsArtifactsName' | ForEach-Object {
            $value = (Get-Variable -Name $_).Value
            Write-Host "::set-output name=$_::$value"
            Add-Content -Path $env:GITHUB_ENV -Value "$_=$value"
          }

      - name: Publish artifacts - apps
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.appsArtifactsName }}
          path: '${{ matrix.project }}/output/Apps/'
          if-no-files-found: ignore

      - name: Publish artifacts - test apps
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.testAppsArtifactsName }}
          path: '${{ matrix.project }}/output/TestApps/'
          if-no-files-found: ignore

      - name: Publish artifacts - test results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: ${{ env.testResultsArtifactsName }}
          path: '${{ matrix.project }}/TestResults.xml'
          if-no-files-found: ignore

      - name: Cleanup
        if: always()
        uses: microsoft/AL-Go-Actions/PipelineCleanup@main
        with:
          parentTelemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}
          Project: ${{ matrix.project }}
  Deploy:
    runs-on: [ windows-latest ] 
    needs: [ Analyze, Build ]
    if: ${{ needs.Analyze.outputs.environmentCount > 0 }}
    strategy:
      matrix:
        environment: ${{ fromJson(needs.Analyze.outputs.environments) }}
      fail-fast: false
    name: Deploy to ${{ matrix.environment }}
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: '${{ github.workspace }}\artifacts'

      - name: EnvName
        id: envName
        run: |
          $envName = '${{ matrix.environment }}'.split(' ')[0]
          Write-Host "::set-output name=envName::$envName"

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          settingsJson: ${{ env.Settings }}
          secrets: '${{ steps.envName.outputs.envName }}-AuthContext,AuthContext'

      - name: AuthContext
        id: authContext
        run: |
          $authContext = [System.Environment]::GetEnvironmentVariable('${{ steps.envName.outputs.envName }}-AuthContext')
          if ($authContext) {
            Write-Host "Using ${{ steps.envName.outputs.envName }}-AuthContext secret"
          }
          else {
            $authContext = [System.Environment]::GetEnvironmentVariable('AuthContext')
            if ($authContext) {
              Write-Host "Using AuthContext secret"
            }
            else {
              Write-Host "::Error::No AuthContext provided"
              exit 1
            }
          }
          Write-Host "::set-output name=authContext::$authContext"
          Write-Host "set-output name=authContext::$authContext"

      - name: Deploy
        uses: microsoft/AL-Go-Actions/Deploy@main
        env:
          authContext: '${{ steps.authContext.outputs.authContext }}'
        with:
          type: 'CD'
          projects: '${{ secrets.Projects }}'
          environmentName: ${{ matrix.environment }}
          artifacts: '${{ github.workspace }}\artifacts'

  postProcess:
    runs-on: [ windows-latest ]
    needs: [ initialization,  Analyze, Build, Deploy ]
    steps:
      - name: Finalizing the workflow
        id: postProcess
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        with: 
          eventId: "DO0091"
          telemetryScopeJson: ${{ needs.initialization.outputs.telemetryScopeJson }}               
