name: Create a new app

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        required: true      
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range (from..to)
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: "N"

defaults:
  run:
    shell: PowerShell
jobs:
  initialization :
    runs-on: windows-latest
    outputs:
      telemetryScope: ${{ steps.init.outputs.telemetryScope }}
      correlationId: ${{ steps.init.outputs.correlationId }}  
    steps:
      - id: init
        uses: microsoft/AL-Go/InitWorkflow@main
        with: 
          workflowName : "DO0092"

  createApp :
    runs-on: windows-latest
    needs : [ initialization ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read settings
        uses: microsoft/AL-Go/ReadSettings@main
        with:
          parentCorrelationId: ${{ needs.initialization.outputs.correlationId }}
          get: type

      - name: Creating a new app
        uses: microsoft/AL-Go/CreateApp@main
        with:
          type: ${{ env.type }}
          name: ${{ github.event.inputs.name }}
          publisher: ${{ github.event.inputs.publisher }}
          idrange: ${{ github.event.inputs.idrange }}
          directCommit: ${{ github.event.inputs.directCommit }}
          parentCorrelationId : ${{ needs.initialization.outputs.correlationId }}

  postProcess :
    runs-on: windows-latest
    needs : [ initialization , createApp ]
    steps:
      - name: Finalizing the workflow
        id : postProcess
        uses: microsoft/AL-Go/workflowpostprocess@main
        with: 
          workflowName : "DO0092"
          telemetryScope : ${{ needs.initialization.outputs.telemetryScope }}