name: Increment Version Number

on:
  workflow_dispatch:
    inputs:
      versionNumber:
        description: New Version Number (Major.Minor)
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  update:
    runs-on: windows-latest

    steps:
      - name: Increment Version Number
        uses: microsoft/AL-Go-Actions/IncrementVersionNumber@main
        with:
          versionNumber: ${{ github.event.inputs.versionNumber }}
          directCommit: ${{ github.event.inputs.directCommit }}
