name: " Pull Power Platform changes"

on:
  workflow_dispatch:
    inputs:
      solutionName:
        description: "Name of the Power Platform solution. (* takes the name from Al-go-settings.json)"
        required: true
        default: "*"
      environment:
        description: "Environment"
        required: true
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: "N"

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

jobs:
  PullChanges:
    runs-on: [windows-latest]
    name: Pull changes from ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell
          eventId: "DO0103"

      - name: EnvName
        id: envName
        shell: powershell
        run: |
          $ErrorActionPreference = "STOP"
          Set-StrictMode -version 2.0
          $envName = '${{ inputs.environment }}'
          Add-Content -Path $env:GITHUB_OUTPUT -Value "envName=$envName"

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          shell: powershell
          settingsJson: ${{ env.Settings }}
          secrets: "${{ steps.envName.outputs.envName }}-AuthContext,${{ steps.envName.outputs.envName }}_AuthContext,AuthContext,${{ steps.envName.outputs.envName }}-EnvironmentName,${{ steps.envName.outputs.envName }}_EnvironmentName,EnvironmentName,projects"
      
      - name: read auth context
        id: authContext
        uses: microsoft/AL-Go-Actions/ReadAuthContext@main
        with:
          shell: powershell
          envName: ${{ steps.envName.outputs.envName }}
          environment: ${{ steps.envName.outputs.envName }}

      - name: Set Power Platform solution name
        id: solutionName
        shell: powershell
        env: 
          _inputSolutionName: ${{ inputs.solutionName }}
        run: |
          $ErrorActionPreference = "STOP"
          Set-StrictMode -version 2.0
          $solutionName = $env:_inputSolutionName
          if ($solutionName -eq "*") {
            write-host "Solution name is not provided. Taking the name from Al-go-settings.json"
            $solutionName = $env:powerPlatformSolutionFolder
          }
          write-host "Solution name: $solutionName"
          Add-Content -Path $env:GITHUB_ENV -Value "powerPlatformSolutionFolder=$solutionName"   

      - name: Export changes from Power Platform 
        uses: microsoft/AL-Go-Actions/PullPowerPlatformChanges@main
        with: 
          shell: powershell
          solutionName: ${{ env.powerPlatformSolutionFolder }}
          directCommit: ${{ inputs.directCommit == 'Y' }}
          deploySettings: ${{ env.deployTo }} 
          authSettings: ${{ env.authContext }}

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        with:
          shell: powershell
          eventId: "DO0103"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
