name: 'Troubleshooting'

on:
  workflow_dispatch:
    inputs:
      displayNamesOfSecrets:
        description: Display the name (not the value) of secrets available to the repository
        type: boolean
        default: true
      useLatestTroubleshooting:
        description: Use the latest troubleshooting action from https://github.com/microsoft/AL-Go
        type: boolean
        default: false

permissions:
  contents: write
  actions: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Troubleshooting:
    name: microsoft/AL-Go-Actions/TroubleShooting@main
    if: github.event.inputs.useLatestTroubleshooting == 'false'
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Troubleshooting
        uses: microsoft/AL-Go-Actions/TroubleShooting@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          displayNamesOfSecrets: ${{ github.event.inputs.displayNamesOfSecrets }}

  LatestTroubleshooting: 
    name: microsoft/AL-Go/Actions/TroubleShooting@main
    if: github.event.inputs.useLatestTroubleshooting == 'true'
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Troubleshooting
        uses: microsoft/AL-Go/Actions/TroubleShooting@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          displayNamesOfSecrets: ${{ github.event.inputs.displayNamesOfSecrets }}
