name: 'Troubleshooting'

on:
  workflow_dispatch:
    inputs:
      useLatestTroubleshooting:
        description: Use the latest troubleshooting action from https://github.com/microsoft/AL-Go
        type: boolean
        default: false

permissions:
  contents: write
  actions: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Troubleshooting:
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Troubleshooting using microsoft/AL-Go-Actions/TroubleShooting@main
        if: github.event.inputs.useLatestTroubleshooting == 'false'
        uses: microsoft/AL-Go-Actions/TroubleShooting@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}

      - name: Troubleshooting using microsoft/AL-Go/Actions/TroubleShooting@main
        if: github.event.inputs.useLatestTroubleshooting == 'true'
        uses: microsoft/AL-Go/Actions/TroubleShooting@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
