name: ' Update AL-Go System Files'

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (current is {TEMPLATEURL})
        required: false
        default: ''
      downloadLatest:
        description: Download latest from template repository
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      updateBranches:
        description: Update all branches, specified in scheduleSettings AL-Go setting? By default, only the current branch is updated.
        type: boolean
        default: false

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  _updateMultipleBranches: ${{ github.event.inputs.updateBranches == 'true' || github.event_name == 'schedule' }}

jobs:
  Initialize:
    runs-on: windows-latest
    name: Initialize
    outputs:
      SupportedBranches: ${{ steps.DetermineBranches.outputs.Result }}
      TemplateUrl: ${{ steps.DetermineTemplateUrl.outputs.TemplateUrl }}
    steps:
      - name: Checkout
        if: ${{ env._updateMultipleBranches }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Read settings
        id: ReadSettings
        if: ${{ env._updateMultipleBranches }}
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          get: scheduleSettings,templateUrl

      - name: Get Supported Branches
        if: ${{ env._updateMultipleBranches }}
        id: GetSupportedBranches
        uses: microsoft/AL-Go-Actions/GetGitBranches@main
        with:
          shell: powershell
          includeBranches: ${{ join(fromJson(env.scheduleSettings).includeBranches, ',') }}

      - name: Determine branches to update
        id: DetermineBranches
        env:
          supportedBranchesJson: ${{ steps.GetSupportedBranches.outputs.Result }}
        shell: powershell
        run: |
            $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0

            if ('${{ env._updateMultipleBranches }}' -eq 'true') {
              $branchesToUpdate = $(ConvertFrom-Json $env:supportedBranchesJson).branches
            }
            else {
              # Default to the current branch
              $branchesToUpdate = @('${{ github.ref_name }}')
            }
            Write-Host "Branches to update: $($branchesToUpdate -join ', ')"
            Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "Result=$(ConvertTo-Json @{ branches = $branchesToUpdate } -Compress)"

      - name: Determine Template URL
        id: DetermineTemplateUrl
        shell: powershell
        run: |
            $templateUrl = $env:templateUrl # Available from ReadSettings step
            $templateUrlAsInput = '${{ github.event.inputs.templateUrl }}'
            if ($templateUrlAsInput) {
              $templateUrl = $templateUrlAsInput
            }

            Write-Host "Using template URL: $templateUrl"
            Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "TemplateUrl=$templateUrl"

  UpdateALGoSystemFiles:
    name: "[${{ matrix.branch }}] Update AL-Go System Files"
    needs: [ Initialize ]
    runs-on: [ windows-latest ]
    strategy:
      matrix:
        branch: ${{ fromJson(needs.Initialize.outputs.SupportedBranches).branches }}
      fail-fast: false

    steps:
      - name: Dump Workflow Information
        uses: microsoft/AL-Go-Actions/DumpWorkflowInfo@main
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ matrix.branch }}

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          get: commitOptions,templateUrl

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Determine templateUrl to use for branch ${{ matrix.branch }}
        id: DetermineBranchTemplateUrl
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0

          $templateUrl = "${{ needs.Initialize.outputs.TemplateUrl }}" # Available from Initialize job
          if ($templateUrl -eq '') {
            $templateUrl = $env:templateUrl # Available from ReadSettings step
          }

          Write-Host "Using template URL: $templateUrl"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "TemplateUrl=$templateUrl"

      - name: Calculate Commit Options
        env:
          directCommit: '${{ github.event.inputs.directCommit }}'
          downloadLatest: '${{ github.event.inputs.downloadLatest }}'
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0

          if('${{ github.event_name }}' -eq 'workflow_dispatch') {
            Write-Host "Using inputs from workflow_dispatch event"

            $directCommit = $env:directCommit
            $downloadLatest = $env:downloadLatest
          }
          else {
            Write-Host "Using inputs from commitOptions setting"
            $commitOptions = $env:commitOptions | ConvertFrom-Json # Available from ReadSettings step

            $directCommit=$(-not $commitOptions.createPullRequest)
            $downloadLatest=$true
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "directCommit=$directCommit"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "downloadLatest=$downloadLatest"

      - name: Update AL-Go system files
        uses: microsoft/AL-Go-Actions/CheckForUpdates@main
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          downloadLatest: ${{ env.downloadLatest }}
          update: 'Y'
          templateUrl: ${{ steps.DetermineBranchTemplateUrl.outputs.TemplateUrl }}
          directCommit: ${{ env.directCommit }}
          updateBranch: ${{ matrix.branch }}

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: powershell
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
