name: ' Update AL-Go System Files'

on:
  workflow_dispatch:
    inputs:
      templateUrl:
        description: Template Repository URL (current is {TEMPLATEURL})
        required: false
        default: ''
      downloadLatest:
        description: Download latest from template repository
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  UpdateALGoSystemFiles:
    needs: [ ]
    runs-on: [ windows-latest ]
    steps:
      - name: Dump Workflow Information
        uses: microsoft/AL-Go-Actions/DumpWorkflowInfo@main
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@main
        with:
          shell: powershell
          eventId: "DO0098"

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell
          get: templateUrl

      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@main
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Override templateUrl
        env:
          templateUrl: ${{ github.event.inputs.templateUrl }}
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $templateUrl = $ENV:templateUrl
          if ($templateUrl) {
            Write-Host "Using Template Url: $templateUrl"
            Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "templateUrl=$templateUrl"
          }

      - name: Calculate Input
        env:
          directCommit: ${{ github.event.inputs.directCommit }}
          downloadLatest: ${{ github.event.inputs.downloadLatest }}
          eventName: ${{ github.event_name }}
          GhTokenWorkflow: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
        run: |
          $errorActionPreference = "Stop";
          $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $directCommit = $ENV:directCommit
          $downloadLatest = $ENV:downloadLatest
          Write-Host $ENV:eventName
          if ($ENV:eventName -eq 'schedule') {
            $downloadLatest = 'true'
            $directCommit = 'true'
            try {
              Write-Host "Running Update AL-Go System Files on a schedule."
              $ENV:GH_TOKEN = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:GhTokenWorkflow))
              $rules = gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$env:GITHUB_REPOSITORY/rules/branches/$env:GITHUB_REF | ConvertFrom-Json
              $branchProtection = gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/$env:GITHUB_REPOSITORY/branches/$env:GITHUB_REF/protection | ConvertFrom-Json
              if (($rules | Where-Object { $_.type -eq 'pull_request' }) -or (($branchProtection.PSObject.Properties.Name -eq "required_pull_request_reviews") -and $branchProtection.enforce_admins.enabled)) {
                Write-Host "Pull request is required for branch $($env:GITHUB_REF)"
                $directCommit = 'false'
              }
              else {
                Write-Host "No pull request required for branch $($env:GITHUB_REF)"
              }
            }
            catch {
              Write-Host "Error occurred while checking branch protection for branch $($env:GITHUB_REF): $_"
            }
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "directCommit=$directCommit"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_ENV -Value "downloadLatest=$downloadLatest"

      - name: Update AL-Go system files
        uses: microsoft/AL-Go-Actions/CheckForUpdates@main
        with:
          shell: powershell
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          downloadLatest: ${{ env.downloadLatest }}
          update: 'Y'
          templateUrl: ${{ env.templateUrl }}
          directCommit: ${{ env.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@main
        with:
          shell: powershell
          eventId: "DO0098"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
