name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy to (default is main)
        required: false
        default: 'main'
      copyToMain:
        description: Additionally deploy templates to main branch? (Y/N) - (NOTE Only use Yes when deploying ordinary releases on microsoft/al-go)
        required: false
        default: 'N'

defaults:
  run:
    shell: PowerShell

jobs:
  Deploy:
    runs-on: [ windows-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: CheckUser
        run: |
          if ("$ENV:GITHUB_REPOSITORY" -eq "freddydk/AL-Go" -and "$ENV:GITHUB_ACTOR" -eq "freddydk") {
            Write-Host "::Error::You cannot run deploy and collect in the microsoft/AL-Go repo"
          }

      - name: Deploy
        run: |
          $ErrorActionPreference = "Stop"
          Set-StrictMode -Version 2.0
          try {
            $token = '${{ Secrets.OrgPAT }}'
            if (!$token) {
              throw "In order to run the Deploy workflow, you need a Secret called OrgPAT containing a valid Personal Access Token"
            }
            else {
              $githubOwner = "$ENV:GITHUB_REPOSITORY_OWNER"
              $settings = [ordered]@{
                  "githubOwner" = $githubOwner
                  "actionsRepo" = "AL-Go-Actions"
                  "perTenantExtensionRepo" = "AL-Go-PTE"
                  "appSourceAppRepo" = "AL-Go-AppSource"
                  "branch" = '${{ github.event.inputs.branch }}'
                  "copyToMain" = ('${{ github.event.inputs.copyToMain }}' -eq 'Y')
                  "localFolder" = ""
                  "baseFolder" = [System.IO.Path]::GetTempPath()
              }
              $settingsFile = Join-Path $settings.baseFolder "deploy.json"
              $settings | ConvertTo-Json | Set-Content $settingsFile -Encoding UTF8
              . ".\Internal\Deploy.ps1" -configName $settingsFile -githubOwner $githubOwner -token $token -github
            }
          }
          catch {
            Write-Host "::Error::Error deploying repositories. The error was $($_.Exception.Message)"
            exit 1
          }
